name: robertmuench
favicon: null
layout_spectrum: 0.04145066300407052
typography_spectrum: 0.3981988348532468
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.19881101767532527
  lightness: 0.907000269042328
  saturation: 0.6240429864265025
  rhythmicContrast: 0.31198489875532687
purpose: []
