typography_spectrum: 0.4019
color:
  brandColors:
    - '#ffffff'
    - '#d9d7be'
    - '#9c876b'
    - '#1b2022'
    - '#803233'
  brandStrength: 0.6875
  lightness: 0.5625
  saturation: 0.3125
  rhythmicContrast: 1
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.39544
analytics:
  google: null
  facebook: null
  twitter: null
author:
  name: Robert M. Münch
  email: robert.muench@robertmuench.ch
name: robertmuench
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Creating cool stuff...
purpose: []
