name: robertmuench
favicon: null
layout_spectrum: 0.39544
typography_spectrum: 0.4019
title: Creating cool stuff...
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#d9d7be'
    - '#9c876b'
    - '#1b2022'
    - '#803233'
  brandStrength: 0.5
  lightness: 0.5625
  saturation: 0.3125
  rhythmicContrast: 0.75
purpose: []
