typography_spectrum: 0.6684555895796211
color:
  brandColors:
    - '#ffffff'
    - '#d9d7be'
    - '#9c876b'
    - '#1b2022'
    - '#803233'
  brandStrength: 0.866453873391383
  lightness: 0.9154762782183209
  saturation: 0.659285319114731
  rhythmicContrast: 0.7961600527352664
github: true
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.8795816562874335
analytics:
  google: null
  facebook: null
  twitter: null
author:
  name: Robert M. Münch
  email: robert.muench@robertmuench.ch
name: robertmuench
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Projekte
    id: a445c554-1044-40c0-883b-5bf05e972b92
    type: content
favicon: null
title: Creating cool stuff...
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://s3-us-west-2.amazonaws.com/the-grid-img/p/7f325cfc8f1ec74ae99dbc0c81b648297e7c0f62.png">
    src: >-
      https://s3-us-west-2.amazonaws.com/the-grid-img/p/7f325cfc8f1ec74ae99dbc0c81b648297e7c0f62.png
    metadata:
      author: []
      related: []
      publisher:
        url: 'https://s3-us-west-2.amazonaws.com'
        name: .s3-us-west-2.amazonaws.com
        favicon: null
        domain: s3-us-west-2.amazonaws.com
      keywords: []
      description: ''
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
description: while thinking out of the box.
purpose:
  - type: internal
    label: About Me
    item: f6407f71-3aca-413f-8e21-492cd9f6299c
